workflows:
  android-build:
    name: Android Build Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.geograph.ical.qu"
      android_signing:
        - key1

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: |
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - elizar.veron@gmail.com
