workflows:
  android-build:
    name: Android Build Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
     
      # Сборка APK
      - echo "Building APK..."
      - ./gradlew assembleRelease
      
      # Сборка AAB
      - echo "Building AAB..."
      - ./gradlew bundleRelease
    artifacts:
     
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - elizar.veron@gmail.com
